import { boolean, integer, numeric, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

const audit = { createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull() };

export const organizations = pgTable("organizations", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), subscriptionTier: text("subscriptionTier").notNull(), trialEndsAt: timestamp("trialEndsAt", { withTimezone: true }).notNull(), maxVehicles: integer("maxVehicles").notNull(), maxUsers: integer("maxUsers").notNull(), currency: text("currency").notNull(), ...audit });
export const organizationSettings = pgTable("organization_settings", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), timezone: text("timezone").notNull().default("Asia/Kolkata"), odometerMaxDailyKm: integer("odometerMaxDailyKm").notNull().default(1000), safetyContactName: text("safetyContactName"), safetyContactPhone: text("safetyContactPhone"), ...audit });
export const users = pgTable("users", { id: uuid("id").defaultRandom().primaryKey(), authUserId: uuid("authUserId").notNull(), orgId: uuid("orgId").notNull(), email: text("email").notNull(), fullName: text("fullName").notNull(), role: text("role").notNull(), ...audit });
export const invitations = pgTable("invitations", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), email: text("email").notNull(), role: text("role").notNull(), tokenHash: text("tokenHash").notNull(), expiresAt: timestamp("expiresAt", { withTimezone: true }).notNull(), acceptedAt: timestamp("acceptedAt", { withTimezone: true }), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull() });
export const vehicles = pgTable("vehicles", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), vin: text("vin").notNull(), licensePlate: text("licensePlate").notNull(), make: text("make").notNull(), model: text("model").notNull(), year: integer("year").notNull(), currentOdometer: numeric("currentOdometer").notNull(), status: text("status").notNull(), ...audit });
export const vehicleAssignments = pgTable("vehicle_assignments", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), vehicleId: uuid("vehicleId").notNull(), driverId: uuid("driverId").notNull(), active: boolean("active").notNull().default(true), ...audit });
export const components = pgTable("components", { id: uuid("id").defaultRandom().primaryKey(), vehicleId: uuid("vehicleId").notNull(), name: text("name").notNull(), expectedLifeKm: numeric("expectedLifeKm").notNull(), lastServicedOdometer: numeric("lastServicedOdometer").notNull(), alertThresholdKm: numeric("alertThresholdKm").notNull() });
export const odometerLogs = pgTable("odometer_logs", { id: uuid("id").defaultRandom().primaryKey(), vehicleId: uuid("vehicleId").notNull(), driverId: uuid("driverId"), reading: numeric("reading").notNull(), source: text("source").notNull(), isFlagged: boolean("isFlagged").notNull(), ...audit });
export const workOrders = pgTable("work_orders", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), vehicleId: uuid("vehicleId").notNull(), assignedMechanicId: uuid("assignedMechanicId"), title: text("title").notNull(), description: text("description"), priority: text("priority").notNull(), status: text("status").notNull(), startedAt: timestamp("startedAt", { withTimezone: true }), completedAt: timestamp("completedAt", { withTimezone: true }), laborHours: numeric("laborHours"), repairNotes: text("repairNotes"), ...audit });
export const workOrderEvidence = pgTable("work_order_evidence", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), workOrderId: uuid("workOrderId").notNull(), uploadedById: uuid("uploadedById").notNull(), fileUrl: text("fileUrl").notNull(), fileKey: text("fileKey"), caption: text("caption"), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull() });
export const inventoryParts = pgTable("inventory_parts", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), sku: text("sku").notNull(), name: text("name").notNull(), binLocation: text("binLocation"), quantityOnHand: integer("quantityOnHand").notNull(), minReorderLevel: integer("minReorderLevel").notNull(), unitCost: numeric("unitCost").notNull() });
export const workOrderParts = pgTable("work_order_parts", { id: uuid("id").defaultRandom().primaryKey(), workOrderId: uuid("workOrderId").notNull(), partId: uuid("partId").notNull(), qtyUsed: integer("qtyUsed").notNull(), unitPrice: numeric("unitPrice").notNull() });
export const vendors = pgTable("vendors", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), name: text("name").notNull(), contactPerson: text("contactPerson"), phone: text("phone").notNull(), email: text("email"), ...audit });
export const purchaseOrders = pgTable("purchase_orders", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), vendorId: uuid("vendorId").notNull(), status: text("status").notNull(), totalCost: numeric("totalCost").notNull(), ...audit });
export const financialRecords = pgTable("financial_records", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), vehicleId: uuid("vehicleId").notNull(), type: text("type").notNull(), category: text("category").notNull(), amount: numeric("amount").notNull(), transactionDate: timestamp("transactionDate", { withTimezone: true }).notNull(), approvalStatus: text("approvalStatus").notNull().default("APPROVED"), approvedById: uuid("approvedById"), approvalReason: text("approvalReason"), reversalOfId: uuid("reversalOfId"), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull() });
export const documents = pgTable("documents", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), vehicleId: uuid("vehicleId"), title: text("title").notNull(), docType: text("docType").notNull(), fileUrl: text("fileUrl").notNull(), fileKey: text("fileKey"), fileChecksum: text("fileChecksum"), fileSizeBytes: integer("fileSizeBytes"), retentionUntil: timestamp("retentionUntil", { withTimezone: true }), expiryDate: timestamp("expiryDate", { withTimezone: true }).notNull(), ...audit });
export const notifications = pgTable("notifications", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), recipientId: uuid("recipientId").notNull(), title: text("title").notNull(), message: text("message").notNull(), type: text("type").notNull(), severity: text("severity").notNull().default("INFO"), sourceType: text("sourceType").notNull().default("SYSTEM"), dedupeKey: text("dedupeKey"), referenceId: uuid("referenceId"), isRead: boolean("isRead").notNull(), acknowledgedAt: timestamp("acknowledgedAt", { withTimezone: true }), escalationLevel: integer("escalationLevel").notNull().default(0), resolvedAt: timestamp("resolvedAt", { withTimezone: true }), ...audit });
export const vehicleIssues = pgTable("vehicle_issues", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), vehicleId: uuid("vehicleId").notNull(), driverId: uuid("driverId").notNull(), title: text("title").notNull(), description: text("description").notNull(), priority: text("priority").notNull(), status: text("status").notNull(), photoUrl: text("photoUrl"), photoKey: text("photoKey"), ...audit });
export const auditEvents = pgTable("audit_events", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), actorId: uuid("actorId"), actorRole: text("actorRole"), action: text("action").notNull(), entityType: text("entityType").notNull(), entityId: uuid("entityId"), summary: text("summary").notNull(), metadata: text("metadata"), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull() });
export const inventoryMovements = pgTable("inventory_movements", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), partId: uuid("partId").notNull(), workOrderId: uuid("workOrderId"), actorId: uuid("actorId"), movementType: text("movementType").notNull(), quantity: integer("quantity").notNull(), unitCost: numeric("unitCost").notNull(), reason: text("reason").notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull() });

export const dvirInspections = pgTable("dvir_inspections", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), vehicleId: uuid("vehicleId").notNull(), driverId: uuid("driverId").notNull(), inspectionType: text("inspectionType").notNull(), status: text("status").notNull(), notes: text("notes"), photoUrl: text("photoUrl"), photoKey: text("photoKey"), ...audit });
export const fuelLogs = pgTable("fuel_logs", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), vehicleId: uuid("vehicleId").notNull(), driverId: uuid("driverId").notNull(), liters: numeric("liters").notNull(), amount: numeric("amount").notNull(), odometer: numeric("odometer").notNull(), station: text("station"), receiptUrl: text("receiptUrl"), ...audit });
