import { boolean, integer, numeric, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

const audit = { createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull() };

export const organizations = pgTable("organizations", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), subscriptionTier: text("subscriptionTier").notNull(), trialEndsAt: timestamp("trialEndsAt", { withTimezone: true }).notNull(), maxVehicles: integer("maxVehicles").notNull(), maxUsers: integer("maxUsers").notNull(), currency: text("currency").notNull(), ...audit });
export const users = pgTable("users", { id: uuid("id").defaultRandom().primaryKey(), authUserId: uuid("authUserId").notNull(), orgId: uuid("orgId").notNull(), email: text("email").notNull(), fullName: text("fullName").notNull(), role: text("role").notNull(), ...audit });
export const invitations = pgTable("invitations", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), email: text("email").notNull(), role: text("role").notNull(), tokenHash: text("tokenHash").notNull(), expiresAt: timestamp("expiresAt", { withTimezone: true }).notNull(), acceptedAt: timestamp("acceptedAt", { withTimezone: true }), ...audit });
export const vehicles = pgTable("vehicles", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), vin: text("vin").notNull(), licensePlate: text("licensePlate").notNull(), make: text("make").notNull(), model: text("model").notNull(), year: integer("year").notNull(), currentOdometer: numeric("currentOdometer").notNull(), status: text("status").notNull(), ...audit });
export const components = pgTable("components", { id: uuid("id").defaultRandom().primaryKey(), vehicleId: uuid("vehicleId").notNull(), name: text("name").notNull(), expectedLifeKm: numeric("expectedLifeKm").notNull(), lastServicedOdometer: numeric("lastServicedOdometer").notNull(), alertThresholdKm: numeric("alertThresholdKm").notNull() });
export const odometerLogs = pgTable("odometer_logs", { id: uuid("id").defaultRandom().primaryKey(), vehicleId: uuid("vehicleId").notNull(), driverId: uuid("driverId"), reading: numeric("reading").notNull(), source: text("source").notNull(), isFlagged: boolean("isFlagged").notNull(), ...audit });
export const workOrders = pgTable("work_orders", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), vehicleId: uuid("vehicleId").notNull(), assignedMechanicId: uuid("assignedMechanicId"), title: text("title").notNull(), description: text("description"), priority: text("priority").notNull(), status: text("status").notNull(), completedAt: timestamp("completedAt", { withTimezone: true }), ...audit });
export const inventoryParts = pgTable("inventory_parts", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), sku: text("sku").notNull(), name: text("name").notNull(), binLocation: text("binLocation"), quantityOnHand: integer("quantityOnHand").notNull(), minReorderLevel: integer("minReorderLevel").notNull(), unitCost: numeric("unitCost").notNull() });
export const workOrderParts = pgTable("work_order_parts", { id: uuid("id").defaultRandom().primaryKey(), workOrderId: uuid("workOrderId").notNull(), partId: uuid("partId").notNull(), qtyUsed: integer("qtyUsed").notNull(), unitPrice: numeric("unitPrice").notNull() });
export const vendors = pgTable("vendors", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), name: text("name").notNull(), contactPerson: text("contactPerson"), phone: text("phone").notNull(), email: text("email"), ...audit });
export const purchaseOrders = pgTable("purchase_orders", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), vendorId: uuid("vendorId").notNull(), status: text("status").notNull(), totalCost: numeric("totalCost").notNull(), ...audit });
export const financialRecords = pgTable("financial_records", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), vehicleId: uuid("vehicleId").notNull(), type: text("type").notNull(), category: text("category").notNull(), amount: numeric("amount").notNull(), transactionDate: timestamp("transactionDate", { withTimezone: true }).notNull() });
export const documents = pgTable("documents", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), vehicleId: uuid("vehicleId"), title: text("title").notNull(), docType: text("docType").notNull(), fileUrl: text("fileUrl").notNull(), fileKey: text("fileKey"), expiryDate: timestamp("expiryDate", { withTimezone: true }).notNull(), ...audit });
export const notifications = pgTable("notifications", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), recipientId: uuid("recipientId").notNull(), title: text("title").notNull(), message: text("message").notNull(), type: text("type").notNull(), referenceId: uuid("referenceId"), isRead: boolean("isRead").notNull(), ...audit });

export const dvirInspections = pgTable("dvir_inspections", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), vehicleId: uuid("vehicleId").notNull(), driverId: uuid("driverId").notNull(), inspectionType: text("inspectionType").notNull(), status: text("status").notNull(), notes: text("notes"), photoUrl: text("photoUrl"), photoKey: text("photoKey"), ...audit });
export const fuelLogs = pgTable("fuel_logs", { id: uuid("id").defaultRandom().primaryKey(), orgId: uuid("orgId").notNull(), vehicleId: uuid("vehicleId").notNull(), driverId: uuid("driverId").notNull(), liters: numeric("liters").notNull(), amount: numeric("amount").notNull(), odometer: numeric("odometer").notNull(), station: text("station"), receiptUrl: text("receiptUrl"), ...audit });
