import { useEffect, useState } from "react";
import { Copy, Mail, RefreshCw, ShieldCheck, UserPlus } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import type { Invitation, InvitationResponse, TeamMember } from "@/types/fleet";

const roleOptions = ["FLEET_MANAGER", "MECHANIC", "TECHNICIAN", "DRIVER", "INVENTORY_MANAGER", "ACCOUNTANT"] as const;

type StateProps = { loading?: boolean; error?: boolean; empty?: boolean; children: React.ReactNode };
function State({ loading, error, empty, children }: StateProps) {
  if (loading) return <div className="workspace-state"><RefreshCw className="spin" size={18} /> Loading live FleetOps data…</div>;
  if (error) return <div className="workspace-state error-state">This workspace could not load from Supabase. Check your session and try again.</div>;
  if (empty) return <div className="workspace-state">No records yet. Use the action above to create the first record.</div>;
  return <>{children}</>;
}

export function TeamWorkspace({ enabled }: { enabled: boolean }) {
  const utils = trpc.useUtils();
  const members = trpc.team.members.useQuery(undefined, { enabled, retry: false });
  const invitations = trpc.team.invitations.useQuery(undefined, { enabled, retry: false });
  const [email, setEmail] = useState("");
  const [role, setRole] = useState<(typeof roleOptions)[number]>("FLEET_MANAGER");
  const [lastInvitation, setLastInvitation] = useState<InvitationResponse | null>(null);
  const [inviteStartedAt, setInviteStartedAt] = useState<number | null>(null);
  const [inviteTimedOut, setInviteTimedOut] = useState(false);
  const invite = trpc.team.invite.useMutation({ onSuccess: (data) => { setLastInvitation(data); setInviteStartedAt(null); setInviteTimedOut(false); setEmail(""); toast.success("Invitation saved", { description: "No email provider is configured; send the redeemable token below to the teammate." }); void utils.team.members.invalidate(); void utils.team.invitations.invalidate(); }, onError: (error) => { setInviteStartedAt(null); setInviteTimedOut(false); toast.error("Invitation failed", { description: error.message }); } });
  const updateRole = trpc.team.updateRole.useMutation({ onSuccess: () => { toast.success("Role updated"); void utils.team.members.invalidate(); }, onError: (error) => toast.error("Role update failed", { description: error.message }) });
  useEffect(() => { if (!invite.isPending || !inviteStartedAt) return; const timer = window.setTimeout(() => { setInviteTimedOut(true); toast.error("Invitation request timed out", { description: "The database did not respond. You can retry without leaving Team." }); }, 10_000); return () => window.clearTimeout(timer); }, [invite.isPending, inviteStartedAt]);
  const invitationRows = invitations.data ?? [];
  const invitationStatus = invitationRows.reduce((counts: Record<string, number>, item: Invitation) => { const status = item.acceptedAt ? "accepted" : new Date(item.expiresAt) < new Date() ? "expired" : "pending"; counts[status] = (counts[status] ?? 0) + 1; return counts; }, {});
  return <>
    <div className="workspace-form panel"><div><div className="panel-kicker">Team access</div><h2>Invite a teammate</h2><p>Choose the least-privileged role needed for the job. Invitations expire after seven days.</p></div><form onSubmit={(event) => { event.preventDefault(); if (email) { setInviteTimedOut(false); setInviteStartedAt(Date.now()); invite.mutate({ email, role }); } }} className="invite-form"><label>Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="teammate@company.com" /></label><label>Role<select value={role} onChange={(event) => setRole(event.target.value as (typeof roleOptions)[number])}>{roleOptions.map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select></label><button type="submit" className="primary-button" disabled={invite.isPending}><UserPlus size={16} />{inviteTimedOut && invite.isPending ? "Waiting for server…" : invite.isPending ? "Creating…" : inviteTimedOut ? "Retry invitation" : "Create invitation"}</button></form>{lastInvitation && <div className="invite-result"><strong>{lastInvitation.delivery === "EMAIL" ? "Invitation email sent." : "Invitation saved; email delivery needs attention."}</strong><span>{lastInvitation.delivery === "EMAIL" ? `The teammate will receive a Join Organization link for ${lastInvitation.email ?? email}.` : `Share the secure Join Organization link with ${lastInvitation.email ?? email}.`}</span><div className="invite-token-row"><code>{lastInvitation.joinUrl ?? lastInvitation.tokenHash}</code><button type="button" className="secondary-button compact-button" onClick={() => { void navigator.clipboard.writeText(lastInvitation.joinUrl ?? lastInvitation.tokenHash ?? ""); toast.success("Join link copied"); }}>Copy join link</button></div>{lastInvitation.deliveryError && <small className="auth-error">Email delivery: {lastInvitation.deliveryError}</small>}</div>}</div>
    <section className="panel workspace-table"><div className="panel-heading"><div><div className="panel-kicker">Organization directory</div><h2>Members</h2></div><span className="signal-chip good"><ShieldCheck size={13} /> RLS protected</span></div><State loading={members.isLoading} error={members.isError} empty={!members.isLoading && !members.isError && !members.data?.length}><div className="member-list">{members.data?.map((member: TeamMember) => <div className="member-row" key={member.id}><div className="mini-avatar">{String(member.fullName ?? member.email).slice(0, 2).toUpperCase()}</div><div><strong>{member.fullName ?? "Unnamed member"}</strong><span>{member.email}</span></div><select className="role-pill" value={member.role} disabled={member.role === "SUPERADMIN" || updateRole.isPending} onChange={(event) => updateRole.mutate({ userId: member.id, role: event.target.value as (typeof roleOptions)[number] })}>{roleOptions.map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select></div>)}</div></State></section>
    <section className="panel workspace-table"><div className="panel-heading"><div><div className="panel-kicker">Invitation ledger</div><h2>Invitation status</h2></div><span className="signal-chip warn"><Mail size={13} /> {invitationStatus.pending ?? 0} pending · {invitationStatus.accepted ?? 0} accepted · {invitationStatus.expired ?? 0} expired</span></div><State loading={invitations.isLoading} error={invitations.isError} empty={!invitations.isLoading && !invitations.isError && !invitations.data?.length}><div className="resource-list">{invitations.data?.map((invite: Invitation) => { const status = invite.acceptedAt ? "Accepted" : new Date(invite.expiresAt) < new Date() ? "Expired" : "Pending"; return <div className="resource-row" key={invite.id}><div><strong>{invite.email}</strong><span>{String(invite.role).replaceAll("_", " ")} · {new Date(invite.expiresAt).toLocaleDateString("en-IN")}</span><code className="invite-token">{invite.tokenHash}</code></div><div className="invite-actions">{status === "Pending" && <button className="icon-button" title="Copy invitation token" aria-label="Copy invitation token" onClick={() => { void navigator.clipboard.writeText(invite.tokenHash ?? ""); toast.success("Invitation token copied"); }}><Copy size={14} /></button>}<span className={`status-label ${status.toLowerCase()}`}>{status}</span></div></div>; })}</div></State></section>
  </>;
}
