import { useState } from "react";
import { ArrowLeft, Check, Copy, Mail, Plus, RefreshCw, ShieldCheck, UserPlus } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const roleOptions = ["FLEET_MANAGER", "MECHANIC", "TECHNICIAN", "DRIVER", "INVENTORY_MANAGER", "ACCOUNTANT"] as const;
type Props = { section: string; session: boolean; onBack: () => void };

function State({ loading, error, empty, children }: { loading?: boolean; error?: boolean; empty?: boolean; children: React.ReactNode }) {
  if (loading) return <div className="workspace-state"><RefreshCw className="spin" size={18} /> Loading live FleetOps data…</div>;
  if (error) return <div className="workspace-state error-state">This workspace could not load from Supabase. Check your session and try again.</div>;
  if (empty) return <div className="workspace-state">No records yet. Use the action above to create the first record.</div>;
  return <>{children}</>;
}

function TeamWorkspace() {
  const utils = trpc.useUtils();
  const members = trpc.team.members.useQuery(undefined, { retry: false });
  const invitations = trpc.team.invitations.useQuery(undefined, { retry: false });
  const [email, setEmail] = useState("");
  const [role, setRole] = useState<(typeof roleOptions)[number]>("FLEET_MANAGER");
  const invite = trpc.team.invite.useMutation({ onSuccess: () => { setEmail(""); toast.success("Invitation created", { description: "Copy the redeemable token from the invitation ledger and send it to the teammate." }); void utils.team.members.invalidate(); void utils.team.invitations.invalidate(); }, onError: (error) => toast.error("Invitation failed", { description: error.message }) });
  const invitationRows = invitations.data ?? [];
  const invitationStatus = invitationRows.reduce((counts: Record<string, number>, item: any) => { const status = item.acceptedAt ? "accepted" : new Date(item.expiresAt) < new Date() ? "expired" : "pending"; counts[status] = (counts[status] ?? 0) + 1; return counts; }, {});
  return <>
    <div className="workspace-form panel"><div><div className="panel-kicker">Team access</div><h2>Invite a teammate</h2><p>Choose the least-privileged role needed for the job. Invitations expire after seven days.</p></div><form onSubmit={(event) => { event.preventDefault(); if (email) invite.mutate({ email, role }); }} className="invite-form"><label>Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="teammate@company.com" /></label><label>Role<select value={role} onChange={(event) => setRole(event.target.value as (typeof roleOptions)[number])}>{roleOptions.map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select></label><button className="primary-button" disabled={invite.isPending}><UserPlus size={16} />{invite.isPending ? "Creating…" : "Create invitation"}</button></form></div>
    <section className="panel workspace-table"><div className="panel-heading"><div><div className="panel-kicker">Organization directory</div><h2>Members</h2></div><span className="signal-chip good"><ShieldCheck size={13} /> RLS protected</span></div><State loading={members.isLoading} error={members.isError} empty={!members.isLoading && !members.isError && !members.data?.length}><div className="member-list">{members.data?.map((member: any) => <div className="member-row" key={member.id}><div className="mini-avatar">{String(member.fullName ?? member.email).slice(0, 2).toUpperCase()}</div><div><strong>{member.fullName ?? "Unnamed member"}</strong><span>{member.email}</span></div><span className="role-pill">{String(member.role).replaceAll("_", " ")}</span></div>)}</div></State></section>
    <section className="panel workspace-table"><div className="panel-heading"><div><div className="panel-kicker">Invitation ledger</div><h2>Invitation status</h2></div><span className="signal-chip warn"><Mail size={13} /> {invitationStatus.pending ?? 0} pending · {invitationStatus.accepted ?? 0} accepted · {invitationStatus.expired ?? 0} expired</span></div><State loading={invitations.isLoading} error={invitations.isError} empty={!invitations.isLoading && !invitations.isError && !invitations.data?.length}><div className="resource-list">{invitations.data?.map((invite: any) => { const status = invite.acceptedAt ? "Accepted" : new Date(invite.expiresAt) < new Date() ? "Expired" : "Pending"; return <div className="resource-row" key={invite.id}><div><strong>{invite.email}</strong><span>{String(invite.role).replaceAll("_", " ")} · {new Date(invite.expiresAt).toLocaleDateString("en-IN")}</span><code className="invite-token">{invite.tokenHash}</code></div><div className="invite-actions">{status === "Pending" && <button className="icon-button" title="Copy invitation token" aria-label="Copy invitation token" onClick={() => { void navigator.clipboard.writeText(invite.tokenHash); toast.success("Invitation token copied"); }}><Copy size={14} /></button>}<span className={`status-label ${status.toLowerCase()}`}>{status}</span></div></div>; })}</div></State></section>
  </>;
}

function NotificationWorkspace() {
  const utils = trpc.useUtils();
  const notifications = trpc.notifications.list.useQuery(undefined, { retry: false });
  const markRead = trpc.notifications.markRead.useMutation({ onSuccess: () => { void utils.notifications.list.invalidate(); void utils.activity.recent.invalidate(); }, onError: (error) => toast.error("Notification update failed", { description: error.message }) });
  const unread = notifications.data?.filter((item: any) => !item.isRead) ?? [];
  return <section className="panel workspace-table"><div className="panel-heading"><div><div className="panel-kicker">Recipient-scoped Supabase alerts</div><h2>Notification center</h2></div><span className={`signal-chip ${unread.length ? "warn" : "good"}`}><Mail size={13} /> {unread.length} unread</span></div><State loading={notifications.isLoading} error={notifications.isError} empty={!notifications.isLoading && !notifications.isError && !notifications.data?.length}><div className="resource-list">{notifications.data?.map((item: any) => <div className={`resource-row ${item.isRead ? "notification-read" : "notification-unread"}`} key={item.id}><div><strong>{item.title}</strong><span>{item.message}</span><small>{new Date(item.createdAt).toLocaleString("en-IN")}</small></div><div className="notification-actions">{item.isRead ? <span className="status-label accepted">Read</span> : <button className="secondary-button compact-button" onClick={() => markRead.mutate({ id: item.id })} disabled={markRead.isPending}><Check size={14} /> Mark read</button>}</div></div>)}</div></State></section>;
}

function ResourceWorkspace({ section }: { section: string }) {
  const utils = trpc.useUtils();
  const vehicles = trpc.vehicles.list.useQuery(undefined, { enabled: section === "Vehicles" || section === "Work orders" || section === "Billing", retry: false });
  const orders = trpc.workOrders.list.useQuery(undefined, { enabled: section === "Work orders", retry: false });
  const inventory = trpc.inventory.list.useQuery(undefined, { enabled: section === "Inventory", retry: false });
  const notifications = trpc.notifications.list.useQuery(undefined, { enabled: section === "Notifications", retry: false });
  const documents = trpc.documents.list.useQuery(undefined, { enabled: section === "Compliance vault", retry: false });
  const financials = trpc.financials.list.useQuery(undefined, { enabled: section === "P&L analytics", retry: false });
  const billing = trpc.billing.status.useQuery(undefined, { enabled: section === "Billing", retry: false });
  const members = trpc.team.members.useQuery(undefined, { enabled: section === "Billing", retry: false });
  const [workOrderTitle, setWorkOrderTitle] = useState("");
  const [workOrderVehicleId, setWorkOrderVehicleId] = useState("");
  const [workOrderPriority, setWorkOrderPriority] = useState<"LOW" | "MEDIUM" | "HIGH" | "CRITICAL">("MEDIUM");
  const createWorkOrder = trpc.workOrders.create.useMutation({ onSuccess: () => { setWorkOrderTitle(""); setWorkOrderVehicleId(""); setWorkOrderPriority("MEDIUM"); toast.success("Work order created"); void utils.workOrders.list.invalidate(); }, onError: (error) => toast.error("Work order creation failed", { description: error.message }) });
  const query = section === "Vehicles" ? vehicles : section === "Work orders" ? orders : section === "Inventory" ? inventory : section === "Notifications" ? notifications : section === "Compliance vault" ? documents : financials;
  const labels: Record<string, string> = { Vehicles: "Fleet register", "Work orders": "Maintenance queue", Inventory: "Parts ledger", Notifications: "Notification center", "Compliance vault": "Compliance documents", "P&L analytics": "Financial ledger" };
  if (section === "Notifications") return <NotificationWorkspace />;
  if (section === "Work orders") return <><div className="workspace-form panel"><div><div className="panel-kicker">Maintenance queue</div><h2>Create work order</h2><p>Create a persisted work order for a vehicle and assign its initial priority.</p></div><form className="invite-form" onSubmit={(event) => { event.preventDefault(); if (!workOrderVehicleId || !workOrderTitle.trim()) return; createWorkOrder.mutate({ vehicleId: workOrderVehicleId, title: workOrderTitle.trim(), priority: workOrderPriority }); }}><label>Vehicle<select required value={workOrderVehicleId} onChange={(event) => setWorkOrderVehicleId(event.target.value)}><option value="">Select a vehicle</option>{vehicles.data?.map((vehicle: any) => <option key={vehicle.id} value={vehicle.id}>{vehicle.licensePlate} · {vehicle.make} {vehicle.model}</option>)}</select></label><label>Title<input required value={workOrderTitle} onChange={(event) => setWorkOrderTitle(event.target.value)} placeholder="Describe the maintenance task" /></label><label>Priority<select value={workOrderPriority} onChange={(event) => setWorkOrderPriority(event.target.value as typeof workOrderPriority)}>{["LOW", "MEDIUM", "HIGH", "CRITICAL"].map((item) => <option key={item} value={item}>{item}</option>)}</select></label><button className="primary-button" disabled={createWorkOrder.isPending || vehicles.isLoading}><Plus size={16} />{createWorkOrder.isPending ? "Creating…" : "Create work order"}</button></form></div><section className="panel workspace-table"><div className="panel-heading"><div><div className="panel-kicker">Persisted Supabase records</div><h2>Maintenance queue</h2></div><span className="signal-chip good"><Check size={13} /> Live query</span></div><State loading={orders.isLoading} error={orders.isError} empty={!orders.isLoading && !orders.isError && !orders.data?.length}><div className="resource-list">{orders.data?.map((row: any) => <div className="resource-row" key={row.id}><div><strong>{row.title}</strong><span>{row.vehicle?.licensePlate ?? "Vehicle unavailable"} · {row.priority}</span></div><span className="resource-meta">{row.status}</span></div>)}</div></State></section></>;
  if (section === "Billing") return <section className="panel workspace-table billing-workspace"><div className="panel-heading"><div><div className="panel-kicker">Subscription control</div><h2>Billing & limits</h2></div><span className={`signal-chip ${billing.data?.writeLocked ? "warn" : "good"}`}><Check size={13} /> {billing.data?.writeLocked ? "Writes locked" : "Live status"}</span></div><State loading={billing.isLoading} error={billing.isError} empty={!billing.data}><div className="billing-grid"><div><span>Current tier</span><strong>{billing.data?.tier?.replaceAll("_", " ")}</strong></div><div><span>Trial days remaining</span><strong>{billing.data?.daysRemaining}</strong></div><div><span>Vehicle capacity</span><strong>{billing.data?.maxVehicles}</strong></div><div><span>Team capacity</span><strong>{billing.data?.maxUsers}</strong></div></div><div className="billing-capacity"><div><span>Vehicle utilization</span><strong>Live from fleet register</strong></div><div className="capacity-track"><span style={{ width: `${billing.data?.maxVehicles ? Math.min(100, ((vehicles.data?.length ?? 0) / billing.data.maxVehicles) * 100) : 0}%` }} /></div><div><span>Team utilization</span><strong>{members.data?.length ?? 0} of {billing.data?.maxUsers ?? "—"} members</strong></div></div><div className="billing-note">{billing.data?.writeLocked ? "The trial has expired and write procedures are locked for this workspace." : `The ${billing.data?.tier?.replaceAll("_", " ")} plan is active. Limits and write permissions are enforced by the FleetOps API.`}</div></State></section>;
  const rows = (query.data ?? []) as any[];
  return <section className="panel workspace-table"><div className="panel-heading"><div><div className="panel-kicker">Persisted Supabase records</div><h2>{labels[section]}</h2></div><span className="signal-chip good"><Check size={13} /> Live query</span></div><State loading={query.isLoading} error={query.isError} empty={!query.isLoading && !query.isError && !rows.length}><div className="resource-list">{rows.map((row) => <div className="resource-row" key={row.id}><div><strong>{row.name ?? row.title ?? row.licensePlate ?? row.sku ?? row.email ?? row.category ?? "Fleet record"}</strong><span>{row.description ?? row.message ?? row.make ? `${row.make ?? ""} ${row.model ?? ""}` : row.status ?? row.role ?? row.docType ?? row.type ?? "Persisted record"}</span></div><span className="resource-meta">{row.status ?? row.quantityOnHand ?? row.amount ?? row.expiresAt ? String(row.status ?? row.quantityOnHand ?? row.amount ?? row.expiresAt) : "—"}</span></div>)}</div></State></section>;
}

export default function FunctionalWorkspace({ section, session, onBack }: Props) {
  if (!session) return <section className="panel auth-gate"><Mail size={24} /><h2>Sign in to open {section}</h2><p>This workspace is connected to Supabase and does not show demo records while signed out.</p><button className="primary-button" onClick={() => toast.info("Use your Supabase Auth sign-in flow to continue.")}><Plus size={16} /> Sign in to sync</button></section>;
  return <div className="functional-workspace"><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Back to command center</button>{section === "Team" ? <TeamWorkspace /> : <ResourceWorkspace section={section} />}</div>;
}
